== Existence par Construction d'une BOG pour une Forme Quadratique en Dimension Finie
:axiom: %Large[bb U]
:def: %huge[triangleq]
:prop: %Large[cl P]
:eg: %Large[cl @eg]
:nota: %huge[i]
:formula: %huge[phi]
:theorem: %huge[top]
:proof: %huge[square]
:model: %huge[fk m]
:lemme: %huge[cl L]
:corollary: %huge[scr C]

include_latex_macros::tex/m3.tex[]

[horizontal]
{theorem}::
Soit %E un espace vectoriel sur %KK, corps commutatif de caractéristique différente de 2,
et %q une forme quadratique sur %E, avec %f dénotant sa forme polaire.
Si %E est de dimension finie %n, alors il existe une base orthogonale pour %E, c'est-à-dire
une base %[Base := (e.1 To e.n)] de %E telle que
%...
  all i,j in range 1 n ss
  i neq j implies f(e.i,e.j) = 0
...%

La preuve fait un usage important de cette formule :
%...
  dim ortho F - dim (F inter ortho E) = dim E - dim F
...%
pour tout sous-espace vectoriel %F de %E . Dans le cas où l'on sait que %[ortho E subset F],
on obtient des résultats encore plus précis :
%...
  F inter ortho E = ortho E implies
  p := dim ortho F - dim ortho E = dim E - dim F
...%
En remarquant que, puisque %[F subset E], %[ortho E subset ortho F] nécéssairement,
on obtient que %p=dim(G) avec %[G oplus ortho E = ortho F] un supplémentaire quelconque.
D'où alors si %[dim E - dim F > 0], nécéssairement %[dim G > 0], ce qui signifie
que l'on peut trouver un vecteur de %E non nul qui ne soit pas dans %F, mais qui soit orthogonal
à tous les éléments de %F .

On prouve par récurrence *finie* que l'on peut construire une suite finie de familles libres orthogonales %[(Base.k)]
où le cardinal de chaque famille est strictement plus grande que la famille précédente, et où le
cardinal de la dernière famille est nécéssairement %n, ce qui prouvera l'existence de bases orthogonales de %E .
On se placera dans le cas particulier où %[Base.k subset Base.[k+1]], où %Base.0 est une base de %[ortho E] .

On définit donc %F.0:=ortho[E], dont on choisit une base quelconque %Base.0 .
Cette famille de %E est orthogonale -- ou vide par abus/définition si %[ortho E = {0}] .
Si %[dim E - dim F.0 = 0], alors %E=ortho[E] et on a trouvé une BOG de %E .
Sinon, il faut trouver un vecteur orthogonal à %F.0 et qui ne soit pas dans %F.0, pour obtenir une famille
orthogonale %Base.1 strictement plus grande que %Base.0 . Comme %[dim E > dim ortho E] et %[ortho E in E],
on peut trouver un supplémentaire %G de %[ortho E] de dimension non nulle, dont on récupère un vecteur non nul
quelconque %x . %x est orthogonal à tout élément de %Base.0, d'où %[Base.1 := Base.0 cup {x}] est une famille
orthogonale de %E strictement plus grande que %Base.0 .

Hérédité : partons d'une famille orthogonale %Base.k, qui contient %Base.0 par hypothèse de récurrence.
Soit %[F.k := Vect(Base.k) et S.k := Vect(Base.k setminus Base.0)] en sorte que %[S.k oplus ortho E = F.k] .
La formule du début donne, puisque %[ortho E subset F.k] :
%...
  p := dim ortho F.k - dim ortho E = dim E - dim F.k
...%
Si %p=0, alors %F.k=E et on a trouvé une BOG de %E (la récurrence est terminée). Sinon,
formule de Grassmann :
%...
  dim E = dim (ortho F.k + dim F.k) =
  dim F.k + dim ortho F.k - dim (ortho F inter F)
  implies dim ortho E = dim (ortho F inter F)

  p := dim ortho F.k - dim ortho E = dim E -
  dim ortho F.k + dim F.k = dim E - dim ortho E
  iff dim ortho G.k + dim ortho E + dim S.k = dim E
...%

